<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kaleidoscope.Core.Async.Abstractions\Kaleidoscope.Core.Async.Abstractions.csproj" />
    <ProjectReference Include="..\Kaleidoscope.Math.Core.Abstractions\Kaleidoscope.Math.Core.Abstractions.csproj" />
  </ItemGroup>

</Project>
