<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kaleidoscope.Core.Abstractions\Kaleidoscope.Core.Abstractions.csproj" />
    <ProjectReference Include="..\Kaleidoscope.Core.Async.Abstractions\Kaleidoscope.Core.Async.Abstractions.csproj" />
    <ProjectReference Include="..\Kaleidoscope.Logic.Beaver.Abstractions\Kaleidoscope.Logic.Beaver.Abstractions.csproj" />
    <ProjectReference Include="..\Kaleidoscope.Logic.Complete.Simple.PresburgerArithmetic\Kaleidoscope.Logic.Complete.Simple.PresburgerArithmetic.csproj" />
    <ProjectReference Include="..\Kaleidoscope.Logic.Complete.Simple.TarskiConsequenceRelation\Kaleidoscope.Logic.Complete.Simple.TarskiConsequenceRelation.csproj" />
    <ProjectReference Include="..\Kaleidoscope.Logic.Complete.Simple.YRPureEqualityExactlyNElements\Kaleidoscope.Logic.Complete.Simple.PureEqualityExactlyNElements.csproj" />
    <ProjectReference Include="..\Kaleidoscope.Logic.Complete.Simple\Kaleidoscope.Logic.Complete.Simple.csproj" />
    <ProjectReference Include="..\Kaleidoscope.Logic.Core.Abstractions\Kaleidoscope.Logic.Core.Abstractions.csproj" />
  </ItemGroup>

</Project>
